name: Release
"on":
  push:
    branches:
      - master
      - next
      - alpha
      - next-major
      - beta
      - "*.x"
jobs:
  windows:
    name: release-windows
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 22
          cache-dependency-path: "package-lock.json"
      - run: npm i
      - run: npm run tauri build
      - uses: actions/upload-artifact@v4
        with:
          name: windows-out
          path: |
            src-tauri/target/release/bundle/msi/my-shortcuts_0.0.0_x64_en-US.msi
            src-tauri/target/release/bundle/nsis/my-shortcuts_0.0.0_x64-setup.exe

  mac:
    name: release-mac
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 22
          cache-dependency-path: "package-lock.json"
      - run: npm i
      - run: npm run tauri build
      - uses: actions/upload-artifact@v4
        with:
          name: mac-out
          path: |
            src-tauri/target/release/bundle/macos/my-shortcuts.app
            src-tauri/target/release/bundle/dmg/my-shortcuts_0.0.0_x64.dmg
  ubuntu:
    name: release-ubuntu
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 22
          cache-dependency-path: "package-lock.json"
      - run: sudo apt update
      - run: sudo apt install -y libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          file \
          libxdo-dev \
          libssl-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev
      - run: npm i
      - run: npm run tauri build
      - uses: actions/upload-artifact@v4
        with:
          name: ubuntu-out
          path: |
            src-tauri/target/release/bundle/deb/my-shortcuts_0.0.0_amd64.deb
            src-tauri/target/release/bundle/appimage/my-shortcuts_0.0.0_amd64.AppImage
  semantic-release:
    name: semantic-release
    runs-on: ubuntu-22.04
    needs: [mac, windows, ubuntu]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 22
          cache-dependency-path: "package-lock.json"
      - run: npm i
      - uses: actions/download-artifact@v4
        with:
          name: mac-out
          path: mac-out
      - uses: actions/download-artifact@v4
        with:
          name: windows-out
          path: windows-out
      - uses: actions/download-artifact@v4
        with:
          name: ubuntu-out
          path: ubuntu-out
      - run: npx semantic-release
        env:
          HUSKY: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
